// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlAES7xVXi6HjtU1f1WYlnl_8WKzuhoU',
    appId: '1:453006389944:android:89a221edf5019285cafa4d',
    messagingSenderId: '453006389944',
    projectId: 'internship-week-7',
    databaseURL: 'https://internship-week-7-default-rtdb.firebaseio.com',
    storageBucket: 'internship-week-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-et0PHHXpUbPfsFP0YT51kT2sIdhAXPI',
    appId: '1:453006389944:ios:d495ac95a9ff2097cafa4d',
    messagingSenderId: '453006389944',
    projectId: 'internship-week-7',
    databaseURL: 'https://internship-week-7-default-rtdb.firebaseio.com',
    storageBucket: 'internship-week-7.firebasestorage.app',
    androidClientId: '453006389944-4hkda6cs6mhnsfl0id82vfssohff352e.apps.googleusercontent.com',
    iosClientId: '453006389944-jbfjrmkvm9qu71j6qkhbresptecu9c4u.apps.googleusercontent.com',
    iosBundleId: 'com.mrfast.completeapp.firebaseStorageApp',
  );
}
