// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdtMO2BXBrfF_39IFFw4jABKNndBwkcbc',
    appId: '1:155607828939:web:989a68e5fed90f551cce4e',
    messagingSenderId: '155607828939',
    projectId: 'firbase-auth-app-affi',
    authDomain: 'firbase-auth-app-affi.firebaseapp.com',
    storageBucket: 'firbase-auth-app-affi.firebasestorage.app',
    measurementId: 'G-3NHJX7GJPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1YRsPa-kdMv64SfIbrxVe7MY6NgZssw',
    appId: '1:155607828939:android:3e41ac39bbd4dcb91cce4e',
    messagingSenderId: '155607828939',
    projectId: 'firbase-auth-app-affi',
    storageBucket: 'firbase-auth-app-affi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUt46-zEXQURwJ8_HXrOzv_nzlu_mU16w',
    appId: '1:155607828939:ios:b59cef58788d66be1cce4e',
    messagingSenderId: '155607828939',
    projectId: 'firbase-auth-app-affi',
    storageBucket: 'firbase-auth-app-affi.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUt46-zEXQURwJ8_HXrOzv_nzlu_mU16w',
    appId: '1:155607828939:ios:b59cef58788d66be1cce4e',
    messagingSenderId: '155607828939',
    projectId: 'firbase-auth-app-affi',
    storageBucket: 'firbase-auth-app-affi.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );
}
